project:
  type: website

website:
  title: ""
  navbar:
    left: 
      - href: index.qmd
        text: Home
        
      - href: research.qmd
        text: Scholarship
        
      - href: projects.qmd
        text: Consulting
        
      - href: portfolio.qmd
        text: Portfolio
        
      - href: cv.qmd
        text: CV
        
    right:
      - icon: github
        href: https://github.com/keitheleejr
      - icon: linkedin
        href: https://www.linkedin.com/in/keitheleejr/
        

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: source

