project:
  type: website

website:
  title: ""
  navbar:
    left: 
      - href: index.qmd
        text: Home
        
      - href: about.qmd
        text: About
        
      - href: research.qmd
        text: Research
        
      - href: projects.qmd
        text: Consulting
        
      - href: files/CV.pdf
        text: CV
        
    right:
      - icon: envelope-at-fill
        href: mailto:Keith Lee <keith@keitheleejr.com>
      - icon: github
        href: https://github.com/keitheleejr
      - icon: linkedin
        href: https://www.linkedin.com/in/keitheleejr/
        

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: source

